[package]
name = "iou"
version = "0.1.0"
description = "io_uring bindings"
repository = "https://github.com/withoutboats/iou"
keywords = ["io_uring", "liburing", "async", "futures"]
license = "MIT OR Apache-2.0"
authors = ["Without Boats <boats@mozilla.com>"]
edition = "2018"

[dependencies]
libc = "0.2.65"
bitflags = "1.2.0"

[dependencies.iou-sys]
version = "0.1.0"
path = "./iou-sys"

[workspace]
