[package]
name = "iou"
version = "0.1.0"
authors = ["Without Boats <boats@mozilla.com>"]
edition = "2018"

[dependencies]
libc = "0.2.62"
bitflags = "1.2.0"

[dependencies.iou-sys]
version = "0.1.0"
path = "./iou-sys"

[workspace]
